# Generated by Django 3.1.7 on 2021-03-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
